CREATE TABLE approval_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR(100) NOT NULL,
    data_id BIGINT,
    operation_type VARCHAR(10) NOT NULL,
    submitted_by VARCHAR(100) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    approval_status VARCHAR(10) NOT NULL,
    approved_by VARCHAR(100),
    approved_at TIMESTAMP,
    new_data JSONB NOT NULL,
    old_data JSONB,
    change_summary TEXT,
    remarks TEXT
);
